import { render, type ComponentChildren } from 'preact';
import { useEffect, useRef, useState } from 'preact/hooks';
import type { Activity, Actor, Lot, Movement, Overview, Patient, RuntimeInfo } from '../shared/contracts.js';
import { getOverview, getSession, initialize, request, signIn } from './api.js';
import './style.css';

const empty: Overview = { patients: [], activities: [], products: [], lots: [], movements: [] };
type Page = 'Today' | 'Patients' | 'Work' | 'Inventory' | 'Manage';
type Editor = { kind: 'patient' | 'activity' | 'product' | 'lot' | 'movement' | 'handoff'; patient?: Patient; lot?: Lot; activity?: Activity; original?: Movement };
function Icon({ name, size = 20 }: { name: string; size?: number }) {
  const paths: Record<string,string> = { Today: 'M3 5h18v16H3z M7 3v4m10-4v4M3 11h18', Patients: 'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M16 4a4 4 0 0 1 0 8m6 9v-2a4 4 0 0 0-3-3.87 M13 7a4 4 0 1 1-8 0 4 4 0 0 1 8 0', Work: 'M9 4h6v4H9z M9 6H5v15h14V6h-4 M8 13h8m-8 4h5', Inventory: 'm3 7 9-4 9 4v10l-9 4-9-4z M3 7l9 4 9-4m-9 4v10', Manage: 'M4 7h16M4 17h16M8 4v6m8 4v6', search: 'm21 21-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0', plus: 'M12 5v14M5 12h14', arrow: 'M5 12h14m-6-6 6 6-6 6', check: 'm5 12 4 4L19 6', close: 'm6 6 12 12M6 18 18 6', leaf: 'M20 3c-9-1-17 4-15 12s15 7 15-12ZM5 19 15 9' };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d={paths[name] || paths.Work}/></svg>;
}
function Badge({ children, tone = '' }: { children: ComponentChildren; tone?: string }) { return <span class={`badge ${tone}`}>{children}</span>; }
function Field({ label, children }: { label: string; children: ComponentChildren }) { return <label class="field"><span>{label}</span>{children}</label>; }
function dateLabel(value: string) { return new Date(`${value}T12:00:00`).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' }); }
function ErrorText({ error }: { error: string }) { return error ? <div role="alert" class="error">{error}</div> : null; }

function App() {
  const [config, setConfig] = useState<RuntimeInfo>();
  const [actor, setActor] = useState<Actor>();
  const [data, setData] = useState<Overview>(empty);
  const [page, setPage] = useState<Page>('Today');
  const [search, setSearch] = useState('');
  const [patientId, setPatientId] = useState<string>();
  const [editor, setEditor] = useState<Editor>();
  const [error, setError] = useState('');
  const [busy, setBusy] = useState(true);
  const [message, setMessage] = useState('');
  const [lastLoaded, setLastLoaded] = useState<Date>();
  async function refresh() { setBusy(true); try { setData(await getOverview()); setLastLoaded(new Date()); setError(''); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  useEffect(() => { void initialize().then(async c => { setConfig(c); const session = await getSession(); setActor(session.actor); await refresh(); }).catch(e => { setError(e.message); setBusy(false); }); }, []);
  const canOperate = !!actor?.roles.includes('Console.Operator');
  const canManage = !!actor?.roles.includes('Inventory.Manager');
  const selected = data.patients.find(p => p.id === patientId);
  const patient = (id: string) => data.patients.find(p => p.id === id);
  const filteredPatients = data.patients.filter(p => `${p.displayName} ${p.tebraId} ${p.dob}`.toLowerCase().includes(search.toLowerCase()));
  const activities = data.activities.filter(a => (!selected || a.patientId === selected.id) && (!search || `${patient(a.patientId)?.displayName} ${a.service}`.toLowerCase().includes(search.toLowerCase())));
  const today = config ? new Intl.DateTimeFormat('en-CA', { timeZone: config.clinicTimezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format() : '';
  const expired = data.lots.filter(l => l.onHand > 0 && l.expiresOn < today);
  const waiting = data.activities.filter(a => a.status !== 'completed');
  const pending = data.activities.filter(a => a.status === 'completed' && a.handoff !== 'filed');
  function navigate(next: Page) { setPage(next); setSearch(''); setPatientId(undefined); }
  function openPatient(p: Patient) { setPatientId(p.id); setPage('Patients'); setSearch(''); }
  const heroText = { Today: ['A clear view of the day.', 'Your patients, next steps, and clinical supplies—in one calm workspace.'], Patients: ['Every patient. One connected view.', 'Operational context linked to the authoritative Tebra chart.'], Work: ['Keep the next step moving.', 'Service progress and chart handoff, tracked separately.'], Inventory: ['Know what’s here. Know what’s next.', 'Traceable stock, patient reservations, and a history behind every change.'], Manage: ['A foundation that can grow.', 'Clear responsibilities and connected workflows for the whole clinic.'] };
  return <div class="app-shell">
    <aside class="sidebar"><a class="brand" href="#" onClick={e => { e.preventDefault(); navigate('Today'); }}><span class="brand-icon"><Icon name="leaf" size={24}/></span><span>inland<span class="brand-sub">CLINIC CONSOLE</span></span></a><div class="workspace-label">YOUR WORKSPACE</div><nav aria-label="Main navigation">{(['Today','Patients','Work','Inventory','Manage'] as Page[]).map(p => <button class={`nav-item ${page === p ? 'active' : ''}`} aria-current={page === p ? 'page' : undefined} onClick={() => navigate(p)}><Icon name={p}/><span>{p}</span>{p === 'Work' && pending.length > 0 && <span class="nav-count">{pending.length}</span>}</button>)}</nav><div class="sidebar-bottom"><span class="connection-dot"/> Alongside Tebra<p>Clinical truth stays in the chart.</p><div class="staff-avatar">IP</div><span class="staff-name">Inland Psychiatric<small>Clinic workspace</small></span></div></aside>
    <div class="main-shell"><header class="topbar"><span class="breadcrumb">Workspace <span>/</span> {page}</span><div class="topbar-actions"><span class="date-label">{new Date().toLocaleDateString('en-US', { timeZone: config?.clinicTimezone || 'America/Los_Angeles', weekday: 'short', month: 'short', day: 'numeric' })}</span><button class="icon-button" title="Refresh records" aria-label="Refresh records" onClick={refresh} disabled={busy}>↻</button>{config?.mode === 'sql' && <button class="button secondary small" onClick={() => void signIn().catch(e => setError(e.message))}>Sign in</button>}</div></header>
      {config?.mode === 'demo' && <div class="demo-banner"><strong>Demonstration workspace</strong><span>Synthetic data only · changes reset when the demo server restarts.</span></div>}
      <main><div class="hero"><div><p class="eyebrow">{page === 'Today' ? 'A LITTLE CLARITY, EVERY DAY' : page.toUpperCase()}</p><h1>{heroText[page][0]}</h1><p class="subtitle">{heroText[page][1]}</p></div>{page !== 'Manage' && (page === 'Inventory' ? canManage : canOperate) && <button class="button primary" onClick={() => setEditor({ kind: page === 'Inventory' ? 'lot' : page === 'Patients' ? 'patient' : 'activity', patient: selected })}><Icon name="plus" size={18}/>{page === 'Inventory' ? 'Add stock lot' : page === 'Patients' ? 'Link patient' : 'New activity'}</button>}</div>
        <ErrorText error={error}/><div class="sr-only" role="status">{message}</div>
        {busy && !lastLoaded && <div class="empty-state">Loading your workspace…</div>}
        {selected && <section class="patient-banner"><div class="avatar">{selected.displayName.slice(0,1)}</div><div><h2>{selected.displayName}</h2><p>DOB {dateLabel(selected.dob)} <span>·</span> Tebra #{selected.tebraId}</p></div><div class="patient-source"><Badge tone="sage">Tebra-linked</Badge><small>Identity checked {new Date(selected.verifiedAt).toLocaleDateString()}</small></div><button class="icon-button" aria-label="Close patient context" onClick={() => setPatientId(undefined)}><Icon name="close"/></button></section>}
        {page === 'Today' && <><div class="metric-grid"><button class="metric lavender" onClick={() => navigate('Work')}><span>Active services</span><strong>{waiting.length}</strong><small>Ready for your next step <Icon name="arrow" size={16}/></small></button><button class="metric peach" onClick={() => navigate('Work')}><span>Awaiting chart handoff</span><strong>{pending.length}</strong><small>Completed · not yet filed <Icon name="arrow" size={16}/></small></button><button class="metric butter" onClick={() => navigate('Inventory')}><span>Stock needing attention</span><strong>{expired.length}</strong><small>Expired lots with stock <Icon name="arrow" size={16}/></small></button></div><div class="today-grid"><section class="panel"><div class="section-heading"><div><h2>Care in motion</h2><p>Open activities across the clinic</p></div><button class="text-button" onClick={() => navigate('Work')}>View work <Icon name="arrow" size={16}/></button></div>{waiting.length ? waiting.slice(0,6).map(a => <button class="activity-row" onClick={() => { const p = patient(a.patientId); if (p) openPatient(p); }}><span class="avatar lavender">{patient(a.patientId)?.displayName.slice(0,1) || '?'}</span><span class="row-title">{patient(a.patientId)?.displayName || 'Linked patient'}<small>{a.service} · {a.status.replace('_',' ')}</small></span><Badge>{a.service}</Badge><Icon name="arrow" size={16}/></button>) : <div class="empty-state">No open activities. Start one when a patient needs a service.</div>}</section><aside class="insight-panel"><span class="insight-icon"><Icon name="leaf" size={28}/></span><p class="eyebrow">CONNECTED, WITH CLARITY</p><h2>A helpful engine.<br/>A trusted chart.</h2><p>Prepare and track the work here. Confirm clinical information in Tebra and finish the documentation handoff there.</p><div class="insight-rule"/><strong>One action at a time</strong><p>Reservations protect patient supply. Inventory use and chart filing remain explicit, separate steps.</p></aside></div></>}
        {(page === 'Patients' || page === 'Work') && <section class="panel"><div class="section-heading"><div><h2>{selected ? 'Patient activities' : page === 'Patients' ? 'Patient directory' : 'Service worklist'}</h2><p>{selected ? 'Service progress and documentation handoff' : 'Search the loaded workspace records'}</p></div><div class="search"><Icon name="search" size={18}/><input aria-label="Search patients and work" placeholder="Search name, chart ID…" value={search} onInput={e => setSearch(e.currentTarget.value)}/></div>{selected && canOperate && <button class="button secondary small" onClick={() => setEditor({ kind: 'activity', patient: selected })}>Add activity</button>}</div>{page === 'Patients' && !selected ? <div class="table-wrap"><table><thead><tr><th>Patient</th><th>Date of birth</th><th>Tebra chart</th><th>Identity verified</th><th/></tr></thead><tbody>{filteredPatients.map(p => <tr><td><button class="patient-link" onClick={() => openPatient(p)}>{p.displayName}</button></td><td>{dateLabel(p.dob)}</td><td>#{p.tebraId}</td><td>{new Date(p.verifiedAt).toLocaleDateString()}</td><td><button class="text-button" onClick={() => openPatient(p)}>Open <Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table>{!filteredPatients.length && <div class="empty-state">No matching patients. Link a verified Tebra chart to begin.</div>}</div> : <div class="table-wrap"><table><thead><tr><th>Patient / service</th><th>Service progress</th><th>Tebra handoff</th><th>Next step</th></tr></thead><tbody>{activities.map(a => <tr><td><strong>{patient(a.patientId)?.displayName || 'Linked patient'}</strong><small>{a.service}</small></td><td><Badge tone={a.status === 'completed' ? 'sage' : ''}>{a.status.replace('_',' ')}</Badge></td><td><Badge tone={a.handoff === 'filed' ? 'sage' : a.handoff === 'prepared' ? 'peach' : ''}>{a.handoff === 'pending' ? 'Not prepared' : a.handoff === 'prepared' ? 'Prepared · not filed' : 'Filed in Tebra'}</Badge></td><td>{canOperate && a.handoff !== 'filed' ? <button class="button secondary small" onClick={() => setEditor({ kind: 'handoff', activity: a, patient: patient(a.patientId) })}>Update activity</button> : <span class="muted">{a.tebraReference || 'View only'}</span>}</td></tr>)}</tbody></table>{!activities.length && <div class="empty-state">No activities here yet.</div>}</div>}</section>}
        {page === 'Inventory' && <><section class="panel"><div class="section-heading"><div><h2>Medication & supply stock</h2><p>Whole stock units · quantities are not medication doses</p></div>{canManage && <button class="button secondary small" onClick={() => setEditor({ kind: 'product' })}><Icon name="plus" size={16}/> Add product</button>}</div><div class="table-wrap"><table><thead><tr><th>Product / lot</th><th>Supply source</th><th>Expiration</th><th>On hand</th><th>Reserved</th><th>Available</th><th/></tr></thead><tbody>{data.lots.map(l => { const p = data.products.find(p => p.id === l.productId); return <tr><td><strong>{p?.name || 'Product'}</strong><small>{p?.strength} · lot {l.lotNumber}</small><small>{l.location}</small></td><td><Badge>{l.ownership}</Badge>{l.ownerPatientId && <small>{patient(l.ownerPatientId)?.displayName || 'Linked owner'}</small>}</td><td><span class={l.expiresOn < today ? 'danger-text' : ''}>{dateLabel(l.expiresOn)}</span>{l.expiresOn < today && <small class="danger-text">Expired</small>}</td><td class="number">{l.onHand}</td><td class="number">{l.reserved}</td><td class="number"><strong>{l.onHand-l.reserved}</strong><small>{p?.unit}s</small></td><td>{(canManage || canOperate) && <button class="button secondary small" onClick={() => setEditor({ kind: 'movement', lot: l })}>Record movement</button>}</td></tr>; })}</tbody></table>{!data.lots.length && <div class="empty-state">Add a product and stock lot, then record its receipt.</div>}</div></section><section class="panel history"><div class="section-heading"><div><h2>Movement history</h2><p>Original entries remain intact. Corrections create a linked reversal.</p></div><Badge>Auditable</Badge></div><div class="table-wrap"><table><thead><tr><th>Movement</th><th>Lot / patient</th><th>Stock change</th><th>Reserved change</th><th>Reason</th><th/></tr></thead><tbody>{data.movements.slice(0,30).map(m => <tr><td><strong>{m.kind === 'use' ? 'Recorded use' : m.kind}</strong><small>{new Date(m.createdAt).toLocaleString('en-US', { timeZone: config?.clinicTimezone })}</small></td><td>{data.lots.find(l => l.id === m.lotId)?.lotNumber}<small>{m.patientId ? patient(m.patientId)?.displayName || 'Linked patient' : 'Clinic stock'}</small></td><td class="number">{m.stockDelta > 0 ? '+' : ''}{m.stockDelta}</td><td class="number">{m.reservedDelta > 0 ? '+' : ''}{m.reservedDelta}</td><td>{m.reason}</td><td>{canManage && m.kind !== 'reverse' && !data.movements.some(r => r.reversesId === m.id) && <button class="text-button" onClick={() => setEditor({ kind: 'movement', lot: data.lots.find(l => l.id === m.lotId), original: m })}>Correct</button>}</td></tr>)}</tbody></table>{!data.movements.length && <div class="empty-state">Stock changes will appear here.</div>}</div></section></>}
        {page === 'Manage' && <div class="manage-grid"><section class="panel manage-card"><Icon name="Patients" size={28}/><h2>Tebra remains authoritative</h2><p>This console stores verified identity links and operational work. It does not synchronize with Tebra or replace orders, diagnoses, medication lists, or signed chart notes.</p><Badge tone="sage">Explicit handoff</Badge></section><section class="panel manage-card"><Icon name="Inventory" size={28}/><h2>Inventory foundations</h2><p>Receipts, patient reservations, releases, use, waste, adjustments, and reversals share one movement history. Patient-owned supply stays with its owner.</p><button class="text-button" onClick={() => navigate('Inventory')}>Manage inventory <Icon name="arrow" size={16}/></button></section><section class="panel manage-card"><Icon name="Work" size={28}/><h2>First build · foundation</h2><p>Clinical decision support, note generation, kiosk integration, transfers, partial-vial tracking, and automated notifications are planned extensions. This build does not perform those actions.</p><Badge>Version 0.1</Badge></section></div>}
        <footer class="workspace-footer"><span><span class="connection-dot"/>{config?.mode === 'demo' ? 'Local synthetic demo' : actor ? 'Connected workspace' : 'Awaiting sign-in'}</span><span>{lastLoaded ? `Loaded ${lastLoaded.toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · refresh for staff updates` : 'No records loaded'} · First 250 records per module</span></footer>
      </main>
    </div>{editor && <EditorDialog editor={editor} data={data} canManage={canManage} onClose={() => setEditor(undefined)} onSaved={async () => { setEditor(undefined); setMessage('Saved successfully.'); await refresh(); }}/>}</div>;
}

function EditorDialog({ editor, data, canManage, onClose, onSaved }: { editor: Editor; data: Overview; canManage: boolean; onClose: () => void; onSaved: () => Promise<void> }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const [error, setError] = useState('');
  const [saving, setSaving] = useState(false);
  const [kind, setKind] = useState(editor.original ? 'reverse' : canManage ? 'receive' : 'reserve');
  const [ownership, setOwnership] = useState('clinic');
  const attempt = useRef<{ payload: string; key: string }>();
  useEffect(() => { dialog.current?.showModal(); }, []);
  const titles = { patient: 'Link a Tebra patient', activity: 'Start a service activity', product: 'Add a stock product', lot: 'Add a stock lot', movement: editor.original ? 'Correct a movement' : 'Record a stock movement', handoff: 'Update service & handoff' };
  const options = (selected?: string) => <><option value="">Select a patient</option>{data.patients.map(p => <option value={p.id} selected={p.id === selected}>{p.displayName} · #{p.tebraId}</option>)}</>;
  async function submit(event: SubmitEvent) {
    event.preventDefault(); if (saving) return;
    const form = new FormData(event.currentTarget as HTMLFormElement);
    const value = (name: string) => String(form.get(name) || '').trim();
    let path = '', method = 'POST', body: unknown;
    switch (editor.kind) {
      case 'patient': path='/patients'; body={ displayName:value('name'), dob:value('dob'), tebraId:value('tebra'), verifiedInTebra:form.get('verified')==='on' }; break;
      case 'activity': path='/activities'; body={ patientId:editor.patient?.id || value('patient'), service:value('service') }; break;
      case 'product': path='/products'; body={ name:value('name'), strength:value('strength'), unit:value('unit'), ndc:value('ndc') || null }; break;
      case 'lot': path='/lots'; body={ productId:value('product'), lotNumber:value('lot'), expiresOn:value('expires'), location:value('location'), ownership, ownerPatientId:ownership==='patient' ? value('patient') : null }; break;
      case 'movement': path='/movements'; body={ lotId:editor.lot!.id, kind, quantity:kind==='reverse' ? 0 : Number(value('quantity')), patientId:editor.original?.patientId || editor.lot?.ownerPatientId || value('patient') || null, reason:value('reason'), reversesId:editor.original?.id || null }; break;
      case 'handoff': path=`/activities/${editor.activity!.id}`; method='PATCH'; body={ expectedVersion:editor.activity!.version, status:value('status'), handoff:value('handoff'), tebraReference:value('reference') || null }; break;
    }
    const payload = JSON.stringify([path,method,body]);
    if (!attempt.current || attempt.current.payload !== payload) attempt.current={ payload, key:crypto.randomUUID() };
    setSaving(true); setError('');
    try { await request(path, method, body, attempt.current.key); await onSaved(); } catch(e) { setError((e as Error).message); } finally { setSaving(false); }
  }
  return <dialog ref={dialog} class="editor-dialog" aria-labelledby="dialog-title" onCancel={e => { e.preventDefault(); if (!saving) onClose(); }}><div class="dialog-header"><div><p class="eyebrow">CLINIC WORKSPACE</p><h2 id="dialog-title">{titles[editor.kind]}</h2></div><button class="icon-button" type="button" aria-label="Close dialog" disabled={saving} onClick={onClose}><Icon name="close"/></button></div><form onSubmit={submit}><div class="dialog-body"><ErrorText error={error}/>
    {editor.kind==='patient' && <><p class="form-note">Use the chart’s verified identity. The clinical record remains in Tebra.</p><Field label="Patient display name"><input name="name" required maxLength={160} autoComplete="off"/></Field><div class="form-grid"><Field label="Date of birth"><input type="date" name="dob" required/></Field><Field label="Tebra chart ID"><input name="tebra" required maxLength={64} pattern="[A-Za-z0-9_-]+"/></Field></div><label class="checkbox"><input type="checkbox" name="verified" required/>I verified this identity and chart ID in Tebra.</label></>}
    {editor.kind==='activity' && <>{editor.patient ? <p class="form-note"><strong>{editor.patient.displayName}</strong> · Tebra #{editor.patient.tebraId}</p> : <Field label="Patient"><select name="patient" required>{options()}</select></Field>}<Field label="Service"><select name="service">{['Injection','UDS','TMS','Samples','Forms'].map(s=><option>{s}</option>)}</select></Field><p class="form-note">Creates an operational activity. This does not create an appointment or order in Tebra.</p></>}
    {editor.kind==='product' && <><Field label="Product name"><input name="name" required maxLength={160}/></Field><Field label="Strength / formulation"><input name="strength" required maxLength={80}/></Field><div class="form-grid"><Field label="Stock counting unit"><select name="unit">{['syringe','kit','tablet','capsule','vial'].map(u=><option>{u}</option>)}</select></Field><Field label="NDC (optional)"><input name="ndc" maxLength={30}/></Field></div><p class="form-note">Count whole units. Partial vials and dose-to-volume conversion are not supported in this foundation build.</p></>}
    {editor.kind==='lot' && <><Field label="Product"><select name="product" required><option value="">Select a product</option>{data.products.map(p=><option value={p.id}>{p.name} · {p.strength} · {p.unit}</option>)}</select></Field><div class="form-grid"><Field label="Lot number"><input name="lot" required maxLength={80}/></Field><Field label="Expiration date"><input name="expires" type="date" required/></Field></div><Field label="Storage location"><input name="location" required maxLength={100} placeholder="Office · cabinet or refrigerator"/></Field><Field label="Supply ownership"><select value={ownership} onChange={e=>setOwnership(e.currentTarget.value)}><option value="clinic">Clinic-owned</option><option value="sample">Clinic sample</option><option value="patient">Patient-specific supply</option></select></Field>{ownership==='patient' && <Field label="Stock owner"><select name="patient" required>{options()}</select></Field>}<p class="form-note">New lots start at zero. Record a receipt to add stock and preserve its movement history.</p></>}
    {editor.kind==='movement' && <><p class="form-note"><strong>Lot {editor.lot?.lotNumber}</strong> · {editor.lot?.onHand} on hand · {editor.lot?.reserved} reserved</p>{editor.original ? <p class="form-note">Reverses the original {editor.original.kind} entry. Quantities and the patient link are preserved automatically.</p> : <><Field label="Movement"><select value={kind} onChange={e=>setKind(e.currentTarget.value)}>{(canManage ? ['receive','reserve','release','use','waste','adjust'] : ['reserve','release','use']).map(k=><option value={k}>{({receive:'Receive stock',reserve:'Reserve for patient',release:'Release reservation',use:'Record use of reserved stock',waste:'Record unreserved waste',adjust:'Reconcile stock count'})[k]}</option>)}</select></Field><Field label={kind==='adjust' ? 'Quantity change (+ add / − remove)' : 'Quantity in whole stock units'}><input name="quantity" type="number" step="1" min={kind==='adjust' ? '-1000000' : '1'} max="1000000" required defaultValue="1"/></Field>{editor.lot?.ownerPatientId ? <p class="form-note">Patient-owned supply: {data.patients.find(p=>p.id===editor.lot?.ownerPatientId)?.displayName}</p> : <Field label={['reserve','release','use'].includes(kind) ? 'Patient' : 'Patient link (optional)'}><select name="patient" required={['reserve','release','use'].includes(kind)}>{options(editor.patient?.id)}</select></Field>}</>}<Field label="Reason / operational reference"><textarea name="reason" required maxLength={300} rows={3}/></Field>{kind==='use' && <p class="form-note">Requires stock reserved for this patient. This records inventory use only; confirm administration and document care in Tebra.</p>}</>}
    {editor.kind==='handoff' && <><p class="form-note"><strong>{editor.patient?.displayName}</strong> · {editor.activity?.service}</p><Field label="Service progress"><select name="status" defaultValue={editor.activity?.status}><option value="planned">Planned</option><option value="in_progress">In progress</option><option value="completed">Completed</option></select></Field><Field label="Tebra documentation handoff"><select name="handoff" defaultValue={editor.activity?.handoff}><option value="pending">Not prepared</option><option value="prepared">Prepared · not yet filed</option><option value="filed">I confirmed it was filed in Tebra</option></select></Field><Field label="Tebra filing reference (required only when filed)"><input name="reference" maxLength={200} placeholder="Encounter date / document reference"/></Field><p class="form-note">Prepared is a staff-reported status. This build does not generate notes or upload to Tebra. Filed handoffs cannot be overwritten.</p></>}
    </div><div class="dialog-footer"><button type="button" class="button secondary" onClick={onClose} disabled={saving}>Cancel</button><button class="button primary" type="submit" disabled={saving}>{saving ? 'Saving…' : editor.kind==='movement' ? 'Save movement' : 'Save'}<Icon name="check" size={17}/></button></div></form></dialog>;
}
render(<App/>, document.getElementById('app')!);
